---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: control-check
spec:
  serviceAccountName: default
  timeout: 3m0s
  taskSpec:
    #  results:
    #    - name: value
    #      type: string
    steps:
      - name: check-step
        image: harbor-repo.vmware.com/dockerhub-proxy-cache/alpine
        script: |
          set -ex
          apk add curl
          
          # curl will block until the service is working (i think)
          # so wait for it to find the server and get a response.
          until curl -sL http://control/info; do
            sleep 1
          done
