---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: control
spec:
  params:
    - name: key
      description: progression key to check against the control server
      type: string
  results:
    - name: value
      type: string
    - name: message
      type: string
  steps:
    - name: check-step
      image: harbor-repo.vmware.com/dockerhub-proxy-cache/alpine
      script: |
        set -ex
        apk add curl
        
        while [[ "$(curl -sL http://control/info)" != *$(params.key)=\"proceed\"* ]]; do
          echo "waiting for control signal" | tee $(results.message.path) 
          sleep 1
        done
        
        # FIXME
        # we cannot append to the messages as that creates variance in the digest value
        # for this resumption
        echo "complete" > $(results.message.path)
        curl -sL http://control/info | grep $(params.key)-value | tee $(results.value.path)
