apiVersion: v1
kind: Service
metadata:
  name: control
spec:
  selector:
    app: control-server
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: control-server
  labels:
    app: control-server
spec:
  containers:
    - name: control-server
      image: harbor-repo.vmware.com/dockerhub-proxy-cache/nginx:1.10
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          scheme: HTTP
          path: /ready
          port: 80
        # give some time to start up otherwise clients will flake
        initialDelaySeconds: 5
        periodSeconds: 1
      volumeMounts:
        - mountPath: /www/data
          name: data
        - mountPath: /etc/nginx
          readOnly: true
          name: nginx-conf
  volumes:
    - name: data
      downwardAPI:
        items:
          - path: "info"
            fieldRef:
              fieldPath: metadata.annotations
    - name: nginx-conf
      configMap:
        name: control-nginx-conf
        items:
          - key: nginx.conf
            path: nginx.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: control-nginx-conf
data:
  nginx.conf: |
    events {
      worker_connections  1024;  ## DefaultDefault: 1024
    }

    http {
      server {
        listen 80;
        server_name http-svc.default.svc.cluster.local;

        location / {
          root /www/data;
        }
        location /ready {
          return 200 'true';
        }

      }
    }
